### ISSUE TITLE
AddJob swallows Cronos.CronFormatException exception

### ISSUE THREAD

**Issue by 9Rune5** [dozer75/Scheduler.NET#2]
When CronJob.Expression returns an invalid cron string (e.g. "*/30 * * * *") nothing is returned that indicates the reason why the job was not properly added.

"Exception thrown: 'Cronos.CronFormatException' in Cronos.dll" is shown in the output window and there is a trace message logged.

The exception should bubble up or the component should log a warning.

**Comment by dozer75** [comment]
Solved in release v0.2.1.
